config/routes.rb
Rails.application.routes.draw do
  resources :comments
  root :to => redirect('/adventures')
  resources :adventures
end

app/models/adventure.rb
class Adventure < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :adventure
end

app/controllers/adventures_controller.rb
class AdventuresController < ApplicationController
  before_action :set_adventure, only: [:show, :edit, :update, :destroy]

  # GET /adventures
  # GET /adventures.json
  def index
    @adventures = Adventure.all
  end

  # GET /adventures/1
  # GET /adventures/1.json
  def show
  end

  # GET /adventures/new
  def new
    @adventure = Adventure.new
  end

  # GET /adventures/1/edit
  def edit
  end

  # POST /adventures
  # POST /adventures.json
  def create
    @adventure = Adventure.new(adventure_params)

    respond_to do |format|
      if @adventure.save
        format.html { redirect_to @adventure, notice: 'Adventure was successfully created.' }
        format.json { render :show, status: :created, location: @adventure }
      else
        format.html { render :new }
        format.json { render json: @adventure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adventures/1
  # PATCH/PUT /adventures/1.json
  def update
    respond_to do |format|
      if @adventure.update(adventure_params)
        format.html { redirect_to @adventure, notice: 'Adventure was successfully updated.' }
        format.json { render :show, status: :ok, location: @adventure }
      else
        format.html { render :edit }
        format.json { render json: @adventure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adventures/1
  # DELETE /adventures/1.json
  def destroy
    @adventure.destroy
    respond_to do |format|
      format.html { redirect_to adventures_url, notice: 'Adventure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adventure
      @adventure = Adventure.find(params[:id])
      @comments = @adventure.comments.all
      @comment = @adventure.comments.build
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adventure_params
      params.require(:adventure).permit(:name, :description, :picture, :visit)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_name, :body, :adventure_id)
    end
end

app/helpers/adventures_helper.rb
module AdventuresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/adventures/_form.html.erb
<%= form_for(@adventure) do |f| %>
  <% if @adventure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adventure.errors.count, "error") %> prohibited this adventure from being saved:</h2>

      <ul>
      <% @adventure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :visit %><br>
    <%= f.date_select :visit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/adventures/edit.html.erb
<h1>Editing Adventure</h1>

<%= render 'form' %>

<%= link_to 'Show', @adventure %> |
<%= link_to 'Back', adventures_path %>

app/views/adventures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Adventures</h1>

<% @adventures.in_groups_of(3) do |group| %>
  <div class="row">
    <% group.compact.each do |adventure| %>
    <div class="col-md-4">
      <%= image_tag adventure.picture_url, width: '100%' if adventure.picture.present?%>
      <h4><%= link_to adventure.name, adventure %></h4>
      <%= adventure.description %>
    </div>
  <% end %>
  </div>

<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th>Visit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adventures.each do |adventure| %>
      <tr>
        <td><%= adventure.name %></td>
        <td><%= adventure.description %></td>
        <td><%= adventure.picture %></td>
        <td><%= adventure.visit %></td>
        <td><%= link_to 'Show', adventure %></td>
        <td><%= link_to 'Edit', edit_adventure_path(adventure) %></td>
        <td><%= link_to 'Destroy', adventure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Adventure', new_adventure_path %>

app/views/adventures/new.html.erb
<h1>New Adventure</h1>

<%= render 'form' %>

<%= link_to 'Back', adventures_path %>

app/views/adventures/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-9">
   <%= image_tag(@adventure.picture_url, :width => 600) if @adventure.picture.present? %>
  
   <h3>Comments</h3>
   <% @comments.each do |comment| %>
       <div>
        <strong><%= comment.user_name %></strong>
        <br />
        <p><%= comment.body %></p>
        <p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>          </div>
    <% end %>
    <%= render 'comments/form' %>

 </div>  
  

  <div class="col-md-3">
    <p><b>Name:</b><%= @adventure.name %></p>
    <p><b>Description:</b><%= @adventure.description %></p>
    <p>

    <%= link_to 'Edit', edit_adventure_path(@adventure) %> |
    <%= link_to 'Destroy', @adventure, data: { confirm: 'Are you sure?' }, method: :delete %> |
    <%= link_to 'Back', adventures_path %>
    </p>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
    <%= f.hidden_field:adventure_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Body</th>
      <th>Adventure</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_name %></td>
        <td><%= comment.body %></td>
        <td><%= comment.adventure_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @comment.user_name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Adventure:</strong>
  <%= @comment.adventure_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LaAdventures</title>
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css">
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <a class="navbar-brand" href="/">The L.A. Adventure App</a>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/adventures">Adventures</a></li>
        <li ><%= link_to 'New Adventure', new_adventure_path %></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>
<footer>
  <div class="container">
    Rails Girls 2015
  </div>
</footer>
<script src="//railsgirls.com/assets/bootstrap.js"></script>

</body>
</html>